# Generated by Django 5.0.7 on 2024-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Tony stark', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
