# Generated by Django 5.0.7 on 2024-08-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_email_contact_name_contact_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
